name: postgresql2
version: 0.5.3
authors:
- Greg Lowe <greg@vis.net.nz>
- Tom Yeh <tomyeh@rikulo.org>
description: >
  A temporary fork of Greg's PostgreSQL driver (xxgreg/postgresql)
  using conserved substitution respecting strings and @@ operators.
  also optimizing the pool implementation aggressivly.
homepage: https://github.com/tomyeh/postgresql

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  crypto: ">=2.0.0"
  convert: ">=1.0.0"

dev_dependencies:
  test: any
  yaml: any
